Disable mypy as it results in a strange error
Mypy failes with
`cratedb_mcp/tool.py:89: error: Missing positional argument "self" in call to "__call__" of "_cached_wrapper"  [call-arg]`
since May 17th 2026.
See #140.
Until the root caused is fixed, lets disable mypy.